app/views/pages/lookup/psa_lookup_results.scala.html
conf/messages

Made changes per ticket (PLA-1561). Pair programmed with Shana.

---

README.md

Reverts hmrc/pensions-lifetime-allowance-frontend#302

Revert "added space to register a change"

---

app/config/frontendAppConfig.scala
app/config/frontendGlobal.scala
app/connectors/PLAConnector.scala
app/connectors/PdfGeneratorConnector.scala
app/controllers/LookupController.scala
app/forms/PSALookupProtectionNotificationNoForm.scala
app/forms/PSALookupSchemeAdministratorReferenceForm.scala
app/models/PSALookupRequest.scala
app/models/PSALookupResult.scala
app/utils/SessionIdSupport.scala
app/views/pages/lookup/ga_metrics.scala.html
app/views/pages/lookup/pla_protection_guidance.scala.html
app/views/pages/lookup/psa_lookup_not_found_print.scala.html
app/views/pages/lookup/psa_lookup_not_found_results.scala.html
app/views/pages/lookup/psa_lookup_protection_notification_no_form.scala.html
app/views/pages/lookup/psa_lookup_results.scala.html
app/views/pages/lookup/psa_lookup_results_print.scala.html
app/views/pages/lookup/psa_lookup_scheme_admin_ref_form.scala.html
conf/app.routes
conf/application-json-logger.xml
conf/application.conf
conf/messages
test/auth/MockConfig.scala
test/controllers/LookupControllerSpec.scala
test/forms/PNNFormSpec.scala
test/forms/PSARefFormSpec.scala

Reverts hmrc/pensions-lifetime-allowance-frontend#300

Revert "Removed all pages relating to psa lookup"

---

project/MicroService.scala
project/plugins.sbt

New build migration

---

project/FrontendBuild.scala
project/plugins.sbt

**Bug fix**
* Dependency uplift to ensure PLA-FE is up to date in accordance with security levels outlined.

DL-1466 Play security fix

---

app/config/frontendAppConfig.scala
conf/application.conf
test/auth/MockConfig.scala

Updated feedback survey url

---

app/common/Dates.scala
app/controllers/WithdrawProtectionController.scala
app/forms/WithdrawDateForm.scala
app/views/helpers/summary/summaryDetails.scala.html
app/views/helpers/templates/formInlineDateInput.scala.html
app/views/pages/result/resultSuccess.scala.html
app/views/pages/withdraw/withdrawConfirm.scala.html
app/views/pages/withdraw/withdrawConfirmation.scala.html
app/views/pages/withdraw/withdrawDate.scala.html
app/views/pages/withdraw/withdrawImplications.scala.html
project/FrontendBuild.scala
project/MicroService.scala
project/plugins.sbt
test/common/DatesSpec.scala
test/common/DisplaySpec.scala
test/controllers/WithdrawProtectionControllerSpec.scala
test/views/pages/ip2016/SummaryViewSpec.scala
test/views/pages/result/ResultSuccessSpec.scala
test/views/pages/withdraw/WithdrawConfirmViewSpec.scala
test/views/pages/withdraw/WithdrawConfirmationViewSpec.scala

**Bug fix**
Fixing issues identified in the DAC report for this service

DL-1698: Fixing Accessibility issues

---

project/FrontendBuild.scala

**Maintenance** 
Updated reactivemongo on pensions lifetime allowance
- [ x ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
- [ x ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
- [ x ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
- [ x ]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
- [ x ]  I've run a dependency check to ensure all dependencies are up to date

Updated simple reactivemongo to version 7.20

---

project/AppDependencies.scala
project/build.properties

DL-3525 Dependency updates

---

app/config/PlaFrontendErrorHandler.scala
conf/messages
conf/messages.cy

DL-2574 Update to live services generic 500 error message.

---

project/AppDependencies.scala

DL-3748 - Updated Mongo Dependency

---

app/config/PlaFrontendErrorHandler.scala
conf/messages
conf/messages.cy
project/AppDependencies.scala

DL-3787 - Error template missing in Welsh

---

app/config/LocalTemplateRenderer.scala
app/connectors/CitizenDetailsConnector.scala
app/connectors/IdentityVerificationConnector.scala
app/connectors/PLAConnector.scala
app/connectors/StubConnector.scala
app/controllers/ReadProtectionsController.scala
build.sbt
project/build.properties
test/connectors/CitizenDetailsConnectorSpec.scala
test/connectors/IdentityVerificationConnectorSpec.scala
test/connectors/PLAConnectorSpec.scala
test/controllers/AmendsControllerSpec.scala
test/controllers/LookupControllerSpec.scala
test/controllers/ReadProtectionsControllerSpec.scala
test/controllers/ResultControllerSpec.scala
test/controllers/UnauthorisedControllerSpec.scala
test/controllers/WithdrawProtectionControllerSpec.scala
test/testHelpers/MockTemplateRenderer.scala

DL-3860
Fixing warnings - mainly deprecated Http methods

DL-3860 Removing warnings

---

conf/application.conf

DL-4131 Remove CSRF bypass

---

app/config/frontendAppConfig.scala
app/views/govuk_wrapper.scala.html
conf/application.conf
project/AppDependencies.scala
test/auth/MockConfig.scala

DL-4233 Adding A11y accessibility statement to PLA

---

build.sbt
project/AppDependencies.scala
project/plugins.sbt
test/auth/package.scala

DL-4488 Upgrading dependencies

---

conf/application.conf

- [X ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
- [X ]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message

DL-4524 - removing company-auth-frontend dependency

---

app/auth/AuthFunction.scala
app/config/frontendAppConfig.scala
app/controllers/UnauthorisedController.scala
conf/application.conf
test/auth/AuthFunctionSpec.scala
test/auth/MockConfig.scala

DL-4824 - PLA continue url is incorrect locally

---

app/common/Display.scala

DL-5346 - summary page has incorrect year in date mask

---

app/forms/AmendPSODetailsForm.scala
app/forms/CommonBinders.scala
app/forms/PSODetailsForm.scala
app/views/helpers/templates/formInlineDateInput.scala.html
app/views/pages/ip2016/psoDetails.scala.html
app/views/playHelpers/templates/formInlineDateInput.scala.html
app/views/playHelpers/templates/formInputMoney.scala.html
app/views/playHelpers/templates/submitButton.scala.html
test/controllers/AmendsControllerSpec.scala
test/controllers/IP2016ControllerSpec.scala
test/forms/AmendPSODetailsFormSpec.scala
test/forms/CommonBindersSpec.scala
test/forms/PSODetailsFormSpec.scala
test/testHelpers/ViewSpecHelpers/ip2016/PsoDetailsViewMessages.scala
test/views/pages/amends/AmendPsoDetailsViewSpec.scala
test/views/pages/ip2016/PsoDetailsViewSpec.scala

DL-8607 - apply-for-ip16-pension-sharing-order-details

---

app/views/pages/ip2016/currentPensions.scala.html
app/views/playHelpers/templates/helpTextAccordion.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/ip2016/CurrentPensionsViewMessages.scala
test/views/pages/amends/AmendCurrentPensionsViewSpec.scala
test/views/pages/ip2016/CurrentPensionsViewSpec.scala

DL-8605 - apply for ip16 current pensions

---

app/views/pages/ip2016/removePsoDetails.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/ip2016/RemovePsoDetailsViewMessages.scala
test/views/pages/ip2016/RemovePsoDetailsViewSpec.scala

DL-8608 - remove Pso details

---

app/views/pages/ip2016/pensionsTakenBefore.scala.html
app/views/playHelpers/templates/formHiddenYesNoRadio.scala.html
app/views/playHelpers/templates/helpTextAccordion.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/ip2016/PensionsTakenBeforeViewMessages.scala
test/views/pages/ip2016/PensionsTakenBeforeViewSpec.scala

DL-8602 pensionsTakenBefore.scala

---

app/views/pages/ip2016/pensionsTakenBetween.scala.html
app/views/playHelpers/templates/formHiddenYesNoRadio.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/ip2016/PensionsTakenBetweenViewMessages.scala
test/views/pages/ip2016/PensionsTakenBetweenViewSpec.scala

DL-8603 - pensions taken between

---

app/views/pages/ip2016/overseasPensions.scala.html
app/views/playHelpers/templates/formHiddenYesNoRadio.scala.html
test/testHelpers/ViewSpecHelpers/ip2016/OverseasPensionsViewMessages.scala
test/views/pages/ip2016/OverseasPensionsViewSpec.scala

DL-8604 - overseas pension

---

app/views/pages/ip2016/pensionDebits.scala.html
test/testHelpers/ViewSpecHelpers/ip2016/PensionDebitsViewMessages.scala
test/views/pages/ip2016/PensionDebitsViewSpec.scala

DL-8606 - pension debits

---

app/views/pages/amends/amendPensionsTakenBefore.scala.html
test/controllers/AmendsControllerSpec.scala
test/views/pages/amends/AmendPensionsTakenBeforeViewSpec.scala

DL-8613 amendPensionsTakenBefore.scala

---

app/views/pages/existingProtections/existingProtections.scala.html
app/views/playHelpers/templates/existingProtections/activeExistingProtection.scala.html
app/views/playHelpers/templates/existingProtections/inactiveExistingProtection.scala.html
app/views/playHelpers/templates/existingProtections/protectionDetails.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/existingProtections/ExistingProtections.scala
test/views/pages/existingProtections/ExistingProtectionsSpec.scala

DL-8610 - existing protections

---

app/views/pages/amends/amendOverseasPensions.scala.html
test/controllers/AmendsControllerSpec.scala
test/views/pages/amends/AmendOverseasPensionsViewSpec.scala

DL-8615 amend-overseas-pensions

---

app/views/pages/amends/amendPensionsTakenBetween.scala.html
test/controllers/AmendsControllerSpec.scala
test/views/pages/amends/AmendPensionsTakenBetweenViewSpec.scala

DL-8614 amend-pensions-taken-between

---

app/views/pages/withdraw/withdrawConfirm.scala.html
conf/messages
conf/messages.cy
test/views/pages/withdraw/WithdrawConfirmViewSpec.scala

Clicking 'Accept' also fails in Staging

DL-8627 - withdraw-confirm

---

app/views/pages/amends/amendPsoDetails.scala.html
test/views/pages/amends/AmendPsoDetailsViewSpec.scala

DL-8624 amend-pso-details

---

app/views/pages/withdraw/withdrawConfirmation.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/withdraw/WithdrawConfirmationSpecMessages.scala
test/views/pages/withdraw/WithdrawConfirmationViewSpec.scala

DL-8628 withdraw confirmation

---

app/controllers/WithdrawProtectionController.scala
app/forms/CommonBinders.scala
app/forms/WithdrawDateForm.scala
app/views/pages/withdraw/withdrawDate.scala.html
test/controllers/WithdrawProtectionControllerSpec.scala
test/forms/CommonBindersSpec.scala
test/forms/WithdrawDateFormSpec.scala
test/testHelpers/ViewSpecHelpers/withdraw/WithdrawDateSpecMessages.scala
test/views/pages/withdraw/WithdrawDateSpec.scala

DL-8626 withdraw date

---

app/views/pages/amends/amendIP14PensionsTakenBetween.scala.html
test/views/pages/amends/AmendIP14PensionsTakenBetweenViewSpec.scala

DL-8634 - amendIP4PensionsTakenBetween

---

app/views/pages/amends/outcomeActive.scala.html
app/views/playHelpers/templates/resultDetails.scala.html
conf/messages
conf/messages.cy
test/controllers/AmendsControllerSpec.scala
test/testHelpers/ViewSpecHelpers/amends/OutcomeActiveViewSpecMessages.scala
test/views/pages/amends/OutcomeActiveViewSpec.scala

DL-8635 - outcome active

---

app/views/pages/amends/amendIP14CurrentPensions.scala.html
test/testHelpers/ViewSpecHelpers/amends/AmendIP14CurrentPensionsViewSpecMessages.scala
test/views/pages/amends/AmendIP14CurrentPensionsViewSpec.scala

DL-8631 amendIP14CurrentPensions.scala

---

app/views/pages/amends/amendIP14OverseasPensions.scala.html
test/views/pages/amends/AmendIP14OverseasPensionsViewSpec.scala

DL-8632 amend ip14 overseas pensions

---

app/views/pages/amends/outcomeInactive.scala.html
conf/messages
conf/messages.cy
test/views/pages/amends/OutcomeInactiveViewSpec.scala

DL-8636 outcome inactive

---

app/views/pages/fallback/noNotificationId.scala.html
conf/messages
conf/messages.cy
test/controllers/AmendsControllerSpec.scala

DL-8639 no notification id

---

app/views/pages/amends/removePsoDebits.scala.html
conf/messages
conf/messages.cy
test/views/pages/amends/RemovePsoDebitsViewSpec.scala

DL-8637 remove pso debits

---

app/views/pages/confirmation/confirmFP.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/CommonMessages.scala
test/testHelpers/ViewSpecHelpers/confirmation/ConfirmFP.scala
test/views/pages/confirmation/ConfirmFPSpec.scala

DL-8638 confirm FP

---

app/views/pages/ivFailure/unauthorised.scala.html
conf/messages
conf/messages.cy

DL-8644 - unauthorised

---

app/views/pages/fallback/technicalError.scala.html

DL-8640 technicalError.scala

---

app/views/pages/ivFailure/technicalIssue.scala.html
conf/messages
conf/messages.cy

DL-8643 - technical-issues

---

app/views/pages/ivFailure/lockedOut.scala.html
conf/messages
conf/messages.cy

lockedOut.scala

---

app/views/pages/timeout.scala.html

DL-8657 timeout page

---

app/views/pages/result/resultRejected.scala.html
conf/app.routes
test/testHelpers/ViewSpecHelpers/result/ResultRejected.scala

resultRejected.scala.html

---

app/views/pages/result/resultSuccess.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/result/ResultSuccess.scala
test/views/pages/result/ResultSuccessSpec.scala

DL-8655 result success

---

app/views/pages/result/manualCorrespondenceNeeded.scala.html
test/testHelpers/ViewSpecHelpers/result/ManualCorrespondenceNeeded.scala
test/views/pages/result/ManualCorrespondenceNeededSpec.scala

DL-8652 Manual Correspondence Needed

---

app/views/pages/result/resultSuccessInactive.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/result/ResultSuccessInactive.scala

DL-8656 - result success inactive

---

app/views/pages/amends/amendCurrentPensions.scala.html
test/views/pages/amends/AmendCurrentPensionsViewSpec.scala

DL-8616 - ammend current pensions

---

app/views/feedback/feedback.scala.html

DL-8910 feedback.scala.html

---

app/controllers/PrintController.scala
app/views/pages/result/resultPrint.scala.html
test/controllers/PrintControllerSpec.scala
test/testHelpers/ViewSpecHelpers/result/ResultPrint.scala
test/views/pages/result/ResultPrintSpec.scala

DL-8653 resultPrint

---

conf/messages.cy

DL-9179: Update welsh

---

project/AppDependencies.scala

DL-9036 remove unused reactive mongo dependency

---

conf/messages.cy

DL-9278 Change Her to His

---

conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/ip2016/PsoDetailsViewMessages.scala
test/testHelpers/ViewSpecHelpers/withdraw/WithdrawDateSpecMessages.scala

Signed-off-by: AhmadNaeemQA <Ahmadzeya.Naeem@digital.hmrc.gov.uk>

DL-9703 Update year for hint text

---

app/constructors/SummaryConstructor.scala
app/views/pages/amends/amendSummary.scala.html
app/views/pages/ip2016/summary.scala.html
app/views/playHelpers/summary/summarySection.scala.html
test/constructors/SummaryConstructorSpec.scala

DL-9704 check-your-answers improvements

---

build.sbt
project/plugins.sbt
test/auth/package.scala

DL-9988 update target JVM version, update java time precision

---

README.md
run.sh
start-dependencies.sh

DL-9881 update readme

---

app/views/pages/existingProtections/existingProtections.scala.html
app/views/playHelpers/templates/existingProtections/activeExistingProtection.scala.html
app/views/playHelpers/templates/existingProtections/inactiveExistingProtection.scala.html
app/views/playHelpers/templates/existingProtections/protectionDetails.scala.html
conf/messages
conf/messages.cy

DL-9790 changed table to summary list

---

conf/application.conf
project/AppDependencies.scala

DL-11774 remove CSP directive

---

app/views/Layout.scala.html
app/views/pages/result/resultPrint.scala.html
project/AppDependencies.scala
project/plugins.sbt
public/stylesheets/pla-print.css
test/views/pages/result/ResultPrintSpec.scala

DL-11854 Updating resultPrint to use Layout

---

conf/messages
conf/messages.cy

DL-12072 correct title for error page

---

app/views/pages/ip2016/summary.scala.html
app/views/pages/result/manualCorrespondenceNeeded.scala.html
app/views/pages/result/resultRejected.scala.html
app/views/pages/result/resultSuccess.scala.html
app/views/pages/result/resultSuccessInactive.scala.html
app/views/pages/timeout.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/ip2016/SummaryViewMessages.scala
test/testHelpers/ViewSpecHelpers/result/ManualCorrespondenceNeeded.scala
test/testHelpers/ViewSpecHelpers/result/ResultRejected.scala
test/testHelpers/ViewSpecHelpers/result/ResultSuccess.scala
test/testHelpers/ViewSpecHelpers/result/ResultSuccessInactive.scala

DL-12265 fix title same as h1

---

app/common/Links.scala
app/constructors/IPApplicationConstructor.scala
app/constructors/SummaryConstructor.scala
app/controllers/IP2016Controller.scala
app/forms/PensionsTakenBetweenForm.scala
app/forms/PensionsUsedBetweenForm.scala
app/models/PensionsUsedBetweenModel.scala
app/utils/CallMap.scala
app/views/pages/amends/amendIP14PensionsTakenBetween.scala.html
app/views/pages/amends/amendPensionsTakenBetween.scala.html
app/views/pages/ip2016/pensionsTakenBetween.scala.html
app/views/pages/ip2016/pensionsUsedBetween.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/connectors/PLAConnectorSpec.scala
test/constructors/IPApplicationConstructorSpec.scala
test/constructors/SummaryConstructorSpec.scala
test/controllers/IP2016ControllerSpec.scala
test/forms/PensionsTakenBetweenFormSpec.scala
test/forms/PensionsUsedBetweenFormSpec.scala
test/testHelpers/ViewSpecHelpers/ip2016/PensionsTakenBetweenViewMessages.scala
test/testHelpers/ViewSpecHelpers/ip2016/PensionsUsedBetweenViewMessages.scala
test/views/pages/amends/AmendIP14PensionsTakenBetweenViewSpec.scala
test/views/pages/amends/AmendPensionsTakenBetweenViewSpec.scala
test/views/pages/ip2016/PensionsTakenBetweenViewSpec.scala
test/views/pages/ip2016/PensionsUsedBetweenViewSpec.scala

DL-12660 break pension between page

---

project/AppDependencies.scala

DL-12314 dependency upgrade

---

app/controllers/IP2016Controller.scala

DL-12540 preserve data from CYA page

---

app/common/Helpers.scala
app/constructors/DisplayConstructors.scala
app/controllers/AmendsController.scala
app/enums/ApplicationStage.scala
app/forms/AmendPensionsTakenBetweenForm.scala
app/forms/AmendPensionsUsedBetweenForm.scala
app/models/amendModels/AmendPensionsUsedetweenModel.scala
app/views/pages/amends/amendIP14PensionsTakenBetween.scala.html
app/views/pages/amends/amendIP14PensionsUsedBetween.scala.html
app/views/pages/amends/amendPensionsTakenBetween.scala.html
app/views/pages/amends/amendPensionsUsedBetween.scala.html
app/views/pages/amends/amendSummary.scala.html
app/views/playHelpers/amends/amendSection.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/controllers/AmendsControllerSpec.scala
test/forms/AmendPensionsTakenBetweenFormSpec.scala
test/forms/AmendPensionsUsedBetweenFormSpec.scala
test/testHelpers/ViewSpecHelpers/amends/AmendIP14PensionsTakenBetweenViewSpecMessages.scala
test/testHelpers/ViewSpecHelpers/ip2016/PensionsTakenBetweenViewMessages.scala
test/views/pages/amends/AmendIP14PensionsTakenBetweenViewSpec.scala
test/views/pages/amends/AmendIP14PensionsUsedBetweenViewSpec.scala
test/views/pages/amends/AmendPensionsTakenBetweenViewSpec.scala
test/views/pages/amends/AmendPensionsUsedBetweenViewSpec.scala

DL-12508 split amend pension taken between page

---

app/views/pages/ip2016/pensionsTaken.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/ip2016/PensionsTakenViewMessages.scala
test/testHelpers/ViewSpecHelpers/ip2016/SummaryViewMessages.scala
test/views/pages/ip2016/PensionsTakenViewSpec.scala

DL-12254 update content

---

app/views/playHelpers/amends/amendSection.scala.html
app/views/playHelpers/summary/summarySection.scala.html

DL-12301 removing overriding styling to change/remove link

---

app/views/pages/amends/amendPensionsTakenBetween.scala.html
app/views/pages/ip2016/pensionsTaken.scala.html
app/views/pages/ip2016/pensionsTakenBetween.scala.html
conf/messages
conf/messages.cy
conf/prod.routes
test/testHelpers/ViewSpecHelpers/ip2016/PensionsTakenBetweenViewMessages.scala
test/views/pages/amends/AmendPensionsTakenBetweenViewSpec.scala
test/views/pages/ip2016/PensionsTakenBetweenViewSpec.scala

DL-12715 Updating pensionsTakenBetween and amendPensionsTakenBetween pages

---

conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/confirmation/ConfirmFP.scala

DL-12847 update title

---

app/views/playHelpers/templates/existingProtections/activeExistingProtection.scala.html
app/views/playHelpers/templates/existingProtections/inactiveExistingProtection.scala.html

DL-12846 add index to amend-link

---

project/AppDependencies.scala

DL-12971 update crown logo

---

app/views/pages/lookup/psa_lookup_results.scala.html
app/views/pages/lookup/psa_lookup_results_print.scala.html
conf/messages
conf/messages.cy

DL-12905 added new lta types

---

app/views/pages/existingProtections/existingProtections.scala.html
app/views/pages/lookup/pla_protection_guidance.scala.html
app/views/pages/lookup/psa_lookup_not_found_results.scala.html
app/views/pages/lookup/psa_lookup_protection_notification_no_form.scala.html
app/views/pages/lookup/psa_lookup_results.scala.html
app/views/pages/lookup/psa_lookup_scheme_admin_ref_form.scala.html
conf/messages
conf/messages.cy
test/testHelpers/ViewSpecHelpers/existingProtections/ExistingProtections.scala
test/testHelpers/ViewSpecHelpers/lookup/PsaLookupProtectionNotificationNoFormSpecMessages.scala
test/testHelpers/ViewSpecHelpers/lookup/PsaLookupResultsSpecMessages.scala
test/testHelpers/ViewSpecHelpers/lookup/PsaLookupSchemeAdminRefFormSpecMessages.scala

DL-13178 accessibility changes

---

app/views/pages/lookup/psa_lookup_protection_notification_no_form.scala.html
test/views/pages/lookup/PsaLookupProtectionNotificationNoFormViewSpec.scala

DL-13177 update back link as per guidelines

---

app/controllers/LookupController.scala
app/controllers/LookupProtectionNotificationController.scala
app/controllers/LookupSchemeAdministratorReferenceController.scala
app/controllers/PrintPdfController.scala
app/views/pages/lookup/psa_lookup_protection_notification_no_form.scala.html
app/views/pages/lookup/psa_lookup_scheme_admin_ref_form.scala.html
conf/app.routes
test/controllers/LookupProtectionNotificationControllerSpec.scala
test/controllers/LookupSchemeAdministratorReferenceControllerSpec.scala
test/controllers/PrintPdfControllerSpec.scala
test/views/lookup/PsaLookupSchemeAdminRefFormViewSpec.scala
test/views/pages/lookup/PsaLookupProtectionNotificationNoFormViewSpec.scala
test/views/pages/lookup/PsaLookupSchemeAdminRefFormViewSpec.scala

DL-13480 split LookupController

---

conf/application.conf

DL-14104 removing frontend-template-provider config

---

app/views/pages/amends/outcomeInactive.scala.html
app/views/pages/result/resultRejected.scala.html
app/views/pages/result/resultSuccess.scala.html
app/views/pages/result/resultSuccessInactive.scala.html
app/views/pages/timeout.scala.html
conf/messages
conf/messages.cy
test/constructors/DisplayConstructorsSpec.scala
test/util/MessagesSpec.scala
test/views/pages/amends/OutcomeInactiveViewSpec.scala
test/views/pages/withdraw/WithdrawConfirmationViewSpec.scala

DL-14167 Moving html out of messages files

---

app/views/pages/amends/amendIP14PensionsTakenBefore.scala.html
test/views/pages/amends/AmendIP14PensionsTakenBeforeViewSpec.scala

DL-14336 IP2014 amend pensions taken before view change

---

app/views/pages/ip2016/pensionsTaken.scala.html
project/plugins.sbt
test/views/pages/ip2016/PensionsTakenViewSpec.scala

DL-14922: corrected two heading h1

---

app/forms/PSALookupProtectionNotificationNoForm.scala

DL-14980: allow FP14 as valid protection

---

project/AppDependencies.scala
project/plugins.sbt
test/views/pages/result/ResultPrintSpec.scala

DL-15081:Dependency Upgrades

---

project/AppDependencies.scala

DL-15294:Rectifying bobby violation

DL-15294:Rectifying bobby violation

---

app/views/pages/ip2016/withdrawnAP2016.scala.html
conf/application.conf
conf/messages
conf/messages.cy
project/AppDependencies.scala

Dl 15312: PYLA: Shutter page - Content update

---

build.sbt
project/AppDependencies.scala
project/build.properties
project/plugins.sbt

DL-15857:Dependency Upgrades

---

app/controllers/redirect/RedirectController.scala
conf/redirect.routes
test/controllers/redirect/RedirectControllerSpec.scala

fix for route compilation error

---

app/connectors/PLAConnector.scala
test/connectors/PLAConnectorSpec.scala

DL-16242 removing unused code

---

conf/application.conf
project/AppDependencies.scala

DL-16805: Gov UK Rebrand 2025

---

app/views/pages/amends/amendSummary.scala.html
build.sbt
conf/application.conf
test/testHelpers/ViewSpecHelpers/amends/AmendSummaryViewSpecMessages.scala
test/views/pages/amends/AmendSummaryViewSpec.scala

DL-16885:Move Withdraw link on amend protection page behind toggle

---

app/common/Helpers.scala
app/common/Strings.scala
app/constructors/DisplayConstructors.scala
app/controllers/AmendControllerCacheHelper.scala
app/controllers/AmendsCurrentPensionController.scala
app/controllers/AmendsOverseasPensionController.scala
app/controllers/AmendsPensionSharingOrderController.scala
app/controllers/AmendsPensionTakenBeforeController.scala
app/controllers/AmendsPensionTakenBetweenController.scala
app/controllers/AmendsPensionUsedBetweenController.scala
app/controllers/AmendsPensionWorthBeforeController.scala
app/controllers/AmendsRemovePensionSharingOrderController.scala
app/controllers/ReadProtectionsController.scala
conf/application.conf
test/constructors/DisplayConstructorsSpec.scala
test/controllers/AmendsCurrentPensionControllerSpec.scala
test/controllers/AmendsOverseasPensionControllerSpec.scala
test/controllers/AmendsPensionSharingOrderControllerSpec.scala
test/controllers/AmendsPensionTakenBeforeControllerSpec.scala
test/controllers/AmendsPensionTakenBetweenControllerSpec.scala
test/controllers/AmendsPensionUsedBetweenControllerSpec.scala
test/controllers/AmendsPensionWorthBeforeControllerSpec.scala
test/controllers/AmendsRemovePensionSharingOrderControllerSpec.scala
test/controllers/ReadProtectionsControllerSpec.scala

- Enable HIP migration feature toggle by default
- Make changes to the reading of statuses for view models and attempt to improve it
- Make changes based on AT runs with feature toggle enabled to ensure correct behaviour

DL-16713 | Enable HIP Migration feature toggle by default

---

app/controllers/AmendsController.scala
test/controllers/AmendsControllerSpec.scala

DL-17416 : Rectifying amendment outcome for notificationId 7 and 14
Bug fix

DL-17416 : Rectifying amendment outcome for notificationId 7 and 14
